version: 2

sources:
  - name: raw
    schema: gz_raw_data
    description: schema holding our raw data
    tables:

      - name: product
        identifier: raw_gz_product
        columns:
          - name: products_id
            description: primary key
            tests:
              - unique
              - not_null
              
      - name: sales
        identifier: raw_gz_sales
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
          - not_null:
              column_name: "(orders_id || '-' || pdt_id)"
        columns:
          - name: orders_id
            description: forms PK when combined with pdt_id
          - name: pdt_id
            description: forms PK when combined with orders_id
        freshness: 
          warn_after:
            count: 90
            period: day
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"
        

      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            description: primary key
            tests:
              - unique
              - not_null

      - name: adwords
        identifier: raw_gz_adwords

      - name: bing
        identifier: raw_gz_bing

      - name: criteo
        identifier: raw_gz_criteo

      - name: facebook
        identifier: raw_gz_facebook


models:
  - name: int_campaigns
    tests:
      - unique:
          column_name: "(date_date || '-' || campaign_key)"
      - not_null:
          column_name: "(date_date || '-' || campaign_key)"
      - accepted_values:
          column_name: paid_source
          values:
            - "Adwords"
            - "Bing"
            - "Criteo"
            - "Facebook"

  - name: int_campaigns_day
    columns:
      - name: date_date
        description: date--primary key
        tests:
          - unique
          - not_null
  
  - name: finance_campaigns_day
    columns:
      - name: date_date
        description: date--primary key
        tests:
          - unique
          - not_null
          
          

              